### ISSUE TITLE
kernel_require.rb:55:in `require': cannot load such file

### ISSUE THREAD

**Issue by jjuris** [asapp/one_wire#2]
Hello 

I would like to use your gem but I am struggling with this error. Can you help please? Thank you

`/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require': cannot load such file -- sysfs_one_wire (LoadError)
    from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from temp:1:in`<main>'
`

> I am using RPi2,  
> - RUBYGEMS VERSION: 2.2.2
>   - RUBY VERSION: 2.1.5 (2014-11-13 patchlevel 273) [arm-linux-gnueabihf]
>   - INSTALLATION DIRECTORY: /var/lib/gems/2.1.0
>   - RUBY EXECUTABLE: /usr/bin/ruby2.1
>   - EXECUTABLE DIRECTORY: /usr/local/bin
>   - SPEC CACHE DIRECTORY: /home/pi/.gem/specs

sudo gem install sysfs_one_wire  ( tried also  with arguments --platform=ruby / --platform=arm-linux )

Fetching: sysfs_one_wire-0.1.0.gem (100%)
Successfully installed sysfs_one_wire-0.1.0
Parsing documentation for sysfs_one_wire-0.1.0
Installing ri documentation for sysfs_one_wire-0.1.0
Done installing documentation for sysfs_one_wire after 2 seconds
1 gem installed

**Comment by elmatou** [comment]
I'm not sure how you are trying to use the gem.
It seem's your script doesn't find the gem in your $LOAD_PATH, do you use Bundler or Rubygems ?
maybe you can paste some part of your code to understand.
It doesn't look like a sysfs_one_wire gem issue.

**Comment by jjuris** [comment]
Hello 
thank you for your help, I already solved issue. 
Instead of require 'sysfs_one_wire' I tried require 'one_wire' and it works :) 

I am closing this issue

**Comment by elmatou** [comment]
Yes... somebody already took one_wire as name for a gem. I had to change it. I will make it clearer
